<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<RootNamespace>AttendenceManagementWeb</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\lib\**" />
    <Content Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <None Remove="wwwroot\lib\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\attendence-management-definitions\attendence-management-definitions.csproj" />
  </ItemGroup>

</Project>
